import "./App.css";
import Main from "./Main";
import { Grid, Typography } from "@mui/material";

function App() {
  return (
    <div className="App">
      <Grid
        container
        spacing={2}
        direction="column"
        alignItems="center"
        justifyContent="center"
      >
        <Grid item xs={12}>
          <Typography variant="h5" gutterBottom>
            A forefront hackathon quizz that uses images generated by{" "}
            <a href="https://openai.com/dall-e-2/">Dall-e</a>
          </Typography>
        </Grid>

        <Grid item xs={12}>
          <Main />
        </Grid>
      </Grid>
    </div>
  );
}

export default App;
