export const people = [
  "Marilyn Monroe",
  "Abraham Lincoln",
  "Nelson Mandela",
  "Queen Elizabeth II",
  "John F. Kennedy",
  "Martin Luther King",
  "Winston Churchill",
  "Bill Gates",
  "Muhammad Ali",
  "Mahatma Gandhi",
  "Mother Teresa",
  "Christopher Columbus",
  "Charles Darwin",
  "Elvis Presley",
  "Albert Einstein",
  "Paul McCartney",
  "Queen Victoria",
  "Pope Francis",
  "Jawaharlal Nehru",
  "Leonardo da Vinci",
  "Vincent Van Gogh",
  "Franklin D. Roosevelt",
  "Pope John Paul II",
  "Thomas Edison",
  "Ludwig Beethoven",
  "Oprah Winfrey",
  "Eva Peron",
  "George Orwell",
  "Dalai Lama",
  "Walt Disney",
  "Neil Armstrong",
  "Peter Sellers",
  "Barack Obama",
  "J.K.Rowling",
  "Pele",
  "Angelina Jolie",
  "Jesse Owens",
  "John Lennon",
  "Henry Ford",
  "Haile Selassie",
  "Joseph Stalin",
  "Michael Jordon",
  "Vladimir Lenin",
  "Ingrid Bergman",
  "Fidel Castro",
  "Leo Tolstoy",
  "Greta Thunberg",
  "Pablo Picasso",
  "Oscar Wilde",
  "Coco Chanel",
  "Charles de Gaulle",
  "Amelia Earhart",
  "John M Keynes",
  "Louis Pasteur",
  "Mikhail Gorbachev",
  "Plato",
  "Adolf Hitler",
  "Sting",
  "Mary Magdalene",
  "Alfred Hitchcock",
  "Michael Jackson",
  "Madonna",
  "Mata Hari",
  "Cleopatra",
  "Grace Kelly",
  "Malala Yousafzai",
  "Steve Jobs",
  "Ronald Reagan",
  "Lionel Messi",
  "Babe Ruth",
  "Bob Geldof",
  "Queen elizabeth",
  "Roger Federer",
  "Sigmund Freud",
  "Woodrow Wilson",
  "Mao Zedong",
  "Katherine Hepburn",
  "Audrey Hepburn",
  "David Beckham",
  "Tiger Woods",
  "Usain Bolt",
  "Carl Lewis",
  "Prince Charles",
  "Joe Biden",
  "Kim Kardashian",
  "Billie Holiday",
  "J.R.R. Tolkien",
  "Billie Jean King",
  "Margaret Thatcher",
];
