export const places = [
  "in the Alps",
  "in Japan",
  "in Paris",
  "on Mount Everest",
  "in New York",
  "in Bali",
  "on Surf wave",
  "on Titanic",
  "in Stockholm",
  "in Berlin",
  "in Jungle",
  "in Sahara",
  "in Malmö",
  "in the Grand canyon",
  "in Bahamas",
  "on top of the Empire state building",
  "in the North Pole",
  "in India",
  "in Space",
  "on the Moon",
  "on Mars",
  "in a Yellow submarine",
];
