export const places = [
  "the Alps",
  "Japan",
  "Paris",
  "Mount Everest",
  "New York",
  "Bali",
  "Surf wave",
  "Titanic",
  "Stockholm",
  "Berlin",
  "Jungle",
  "Sahara",
  "Malmö",
  "Grand canyon",
  "The Bahamas",
  "on top of the Empire state building",
  "North Pole",
  "India",
  "Space",
  "Moon",
  "Mars",
  "yellow submarine",
];
