export const verbs = [
  "riding a bike",
  "driving a car",
  "swimming",
  "running a marathon",
  "driving a motorcycle",
  "riding a rollercoaster",
  "skiing",
  "playing basketball",
  "smoking a cigarette",
  "programming",
  "dancing",
  "singing",
  "playing football",
  "playing golf",
  "playing hockey",
  "playing 8-bit computer game",
  "playing a card game",
  "bowling",
  "cleaning teeth",
  "jumping",
  "dancing ballet",
  "sleeping",
  "dancing hip hop",
  "sitting on toilet",
  "playing piano",
  "washing a car",
  "showing magic tricks",
  "wearing beach clothes",
  "wearing spacesuit",
  "looking gorgeous",
  "visiting Safari",
  "making tattoo",
  "cooking soup",
  "roasting marshmallows",
  "making a mini city out of toilet paper rolls",
];
