export const verbs = [
  "riding a bike",
  "driving a car",
  "swimming",
  "running a marathon",
  "driving a motorcycle",
  "riding a rollercoaster",
  "skiing",
  "playing basketball",
  "smoking a cigarette",
  "programming",
  "dancing",
  "singing",
  "playing fotboll",
  "playing hockey",
  "cleaning teeth",
  "jumping",
  "dancing ballet",
  "sleeping",
  "dancing hip hop",
  "sitting on toilet",
];
